#!/usr/bin/env python3

"""
Sample script to analyze a JSON-formatted DNS log generated by Zeek.

Usage:
Generate a JSON-formatted DNS log using Zeek, then run the script.
$ zeek -r ./dns.pcap local Log::default_logdir=./ -C LogAscii::use_json=T
$ ./analyze_zeek_dns_json_log.py -f dns.log 
"""

import datetime
import argparse
import json

parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', type=str, required=True, help='Specify the JSON format file generated by zeek')
args = parser.parse_args()
json_file = args.file

def load_log_file(file=''):
    """
    Load the zeek log and put them into the list
    """
    dns_log = list()
    with open('dns.log', 'r') as f:
        for line in f:
            json_line = json.loads(line)
            dns_log.append(json_line)
    return dns_log

def count_result_code(log='dns_log'):
    """
    Count the number of unique result codes.
    """
    result = dict()
    for i in dns_log:
        if 'rcode_name' in i.keys():
            if i['rcode_name'] in result.keys():
                result[i['rcode_name']] += 1
            else:
                result[i['rcode_name']] = 1
    return result

def count_src_ip(log='dns_log'):
    """
    Count the number of unique source IP addresses
    """
    result = dict()
    for i in dns_log:
        if 'id.orig_h' in i.keys():
            if i['id.orig_h'] in result.keys():
                result[i['id.orig_h']] += 1
            else:
                result[i['id.orig_h']] = 1
    return result

def count_qtype(log='dns_log'):
    """
    Count the number of unique query types
    """
    result = dict()
    for i in dns_log:
        if 'qtype_name' in i.keys():
            if i['qtype_name'] in result.keys():
                result[i['qtype_name']] += 1
            else:
                result[i['qtype_name']] = 1
    return result

if __name__ == "__main__":
    # load the log file, put them into the list
    dns_log = load_log_file(file=json_file)

    # print timestamp
    start_time = datetime.datetime.fromtimestamp(dns_log[0]['ts']).strftime('%c')
    end_time = datetime.datetime.fromtimestamp(dns_log[-1]['ts']).strftime('%c')
    print(f"Result from {start_time} to {end_time}")

    # count result codes
    result = count_result_code()
    print(result)

    # count source IP addresses
    result = count_src_ip()
    print(result)

    # count query types
    result = count_qtype()
    print(result)
